=== KarlaSmuk/Parkovi_Hrvatske/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://example.com/schema.json",
    "title": "Parkovi Hrvatske",
    "description": "Otvoreni skup Parkova Hrvatske",
    "type": "array",
    "items": {
        "title": "Park",
        "description": "Objekt koji sadrži atribute parka.",
        "type": "object",
        "required": [
            "park",
            "tip",
            "godina_osnutka",
            "povrsina",
            "vrh",
            "zupanija",
            "atrakcija",
            "dogadjaj_godine",
            "zivotinje"
        ],
        "properties": {
            "park": {
                "description": "Naziv parka.",
                "type": "string"
            },
            "tip": {
                "description": "Tip parka (Park prirode ili Nacionalni park).",
                "type": "string"
            },
            "godina_osnutka": {
                "description": "Godina osnutka parka.",
                "type": "integer"
            },
            "povrsina": {
                "description": "Površina parka u km²",
                "type": [
                    "number",
                    "integer"
                ]
            },
            "vrh": {
                "title" : "Najviši vrh.",
                "description": "Objekt koji sadrži atribute najvišeg vrha parka.",
                "type": "object",
                "required": [
                    "naziv",
                    "visina"
                ],
                "properties": {
                    "naziv": {
                        "description": "Naziv najvišeg vrha parka.",
                        "type": [
                            "null",
                            "string"
                        ]
                    },
                    "visina": {
                        "title": "The visina Schema",
                        "description": "Visina najvišeg vrha u metrima ( m ).",
                        "type": [
                            "null",
                            "integer"
                        ]
                    }
                }
            },
            "zupanija": {
                "title" : "Županije/a",
                "description": "Naziv županije ili županija u kojoj se park nalazi.",
                "type": "array",
                "items": {
                    "title": "Županija",
                    "description": "Županija koja se nalazi u parku.",
                    "type": "string"
                }
            },
            "atrakcija": {
                "description": "Najpoznatija atrakcija",
                "type": "string"
            },
            "dogadjaj_godine": {
                "description": "Najpoznatiji događaj u godini.",
                "type": "string"
            },
            "zivotinje": {
                "title" : "Životinje",
                "description": "Neke od životinja koje se može vidjeti u parku.",
                "type": "array",
                "items": {
                    "title": "Žvotinja",
                    "description": "Objekt koji sadrži ime i vrstu životinje.",
                    "type": "object",
                    "required": [
                        "naziv",
                        "vrsta"
                    ],
                    "properties": {
                        "naziv": {
                            "description": "Naziv životinje.",
                            "type": "string"
                        },
                        "vrsta": {
                            "description": "Vrsta životinje.",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== KarlaSmuk/Parkovi_Hrvatske/frontend/public/data/parkovi.json
[
    {
        "park": "Brijuni",
        "tip": "Nacionalni park",
        "godina_osnutka": 1983,
        "povrsina": 33.9,
        "vrh": {
            "naziv": null,
            "visina": null
        },
        "zupanija": [
            "Istarska"
        ],
        "atrakcija": "Vidikovac na Ciprovcu",
        "dogadjaj_godine": "Dani dinosaura u travnju",
        "zivotinje": [
            {
                "naziv": "Dupin",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Morska kornjača",
                "vrsta": "gmaz"
            }
        ]
    },
    {
        "park": "Krka",
        "tip": "Nacionalni park",
        "godina_osnutka": 1985,
        "povrsina": 109,
        "vrh": {
            "naziv": null,
            "visina": null
        },
        "zupanija": [
            "Šibensko-kninska"
        ],
        "atrakcija": "Skradinski buk",
        "dogadjaj_godine": "Krkino kulturno ljeto",
        "zivotinje": [
            {
                "naziv": "Čovječja ribica",
                "vrsta": "vodozemac"
            },
            {
                "naziv": "Vidra",
                "vrsta": "sisavac"
            }
        ]
    },
    {
        "park": "Mljet",
        "tip": "Nacionalni park",
        "godina_osnutka": 1960,
        "povrsina": 53.7,
        "vrh": {
            "naziv": null,
            "visina": null
        },
        "zupanija": [
            "Dubrovačko-neretvanska"
        ],
        "atrakcija": "Otočić Svete Marije",
        "dogadjaj_godine": "Obilježavanje godišnjice osnivanja",
        "zivotinje": [
            {
                "naziv": "Morski vranac",
                "vrsta": "ptica"
            },
            {
                "naziv": "Sredozemni galeb",
                "vrsta": "ptica"
            }
        ]
    },
    {
        "park": "Plitvička jezera",
        "tip": "Nacionalni park",
        "godina_osnutka": 1949,
        "povrsina": 296.8,
        "vrh": {
            "naziv": "Seliški vrh",
            "visina": 1279
        },
        "zupanija": [
            "Karlovačka",
            "Ličko-senjska"
        ],
        "atrakcija": "Gornja jezera",
        "dogadjaj_godine": "Plitvički maraton u lipnju",
        "zivotinje": [
            {
                "naziv": "Medvjed",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Vidra",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Vuk",
                "vrsta": "sisavac"
            }
        ]
    },
    {
        "park": "Risnjak",
        "tip": "Nacionalni park",
        "godina_osnutka": 1953,
        "povrsina": 63.5,
        "vrh": {
            "naziv": "Veliki risnjak",
            "visina": 1528
        },
        "zupanija": [
            "Primorsko-goranska"
        ],
        "atrakcija": "Izvor Kupe",
        "dogadjaj_godine": "Furmanski dan u kolovozu",
        "zivotinje": [
            {
                "naziv": "Medvjed",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Ris",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Vuk",
                "vrsta": "sisavac"
            }
        ]
    },
    {
        "park": "Biokovo",
        "tip": "Park prirode",
        "godina_osnutka": 1981,
        "povrsina": 194,
        "vrh": {
            "naziv": "Sveti Jure",
            "visina": 1762
        },
        "zupanija": [
            "Splitsko-dalmatinska"
        ],
        "atrakcija": "Vidikovac Sv. Jure",
        "dogadjaj_godine": "Međunarodna brdska utrka u svibnju",
        "zivotinje": [
            {
                "naziv": "Muflon",
                "vrsta": "sisavac"
            },
            {
                "naziv": "Poskok",
                "vrsta": "zmija"
            },
            {
                "naziv": "Vuk",
                "vrsta": "sisavac"
            }
        ]
    },
    {
        "park": "Kopački rit",
        "tip": "Park prirode",
        "godina_osnutka": 1976,
        "povrsina": 231,
        "vrh": {
            "naziv": null,
            "visina": null
        },
        "zupanija": [
            "Osječko-baranjska"
        ],
        "atrakcija": "Šetnica bijelog lopoča",
        "dogadjaj_godine": "Dan otvorenih vrata u srpnju",
        "zivotinje": [
            {
                "naziv": "Orao štekavac",
                "vrsta": "ptica"
            },
            {
                "naziv": "Vidra",
                "vrsta": "sisavac"
            }
        ]
    },
    {
        "park": "Medvednica",
        "tip": "Park prirode",
        "godina_osnutka": 1981,
        "povrsina": 179.4,
        "vrh": {
            "naziv": "Sljeme",
            "visina": 1035
        },
        "zupanija": [
            "Grad Zagreb",
            "Krapinsko-zagorska",
            "Zagrebačka"
        ],
        "atrakcija": "Petsto Horvatovih stuba",
        "dogadjaj_godine": "Snježna kraljica",
        "zivotinje": [
            {
                "naziv": "Močvarni plavac",
                "vrsta": "leptir"
            },
            {
                "naziv": "Poskok",
                "vrsta": "zmija"
            }
        ]
    },
    {
        "park": "Papuk",
        "tip": "Park prirode",
        "godina_osnutka": 1999,
        "povrsina": 336,
        "vrh": {
            "naziv": "Papuk",
            "visina": 953
        },
        "zupanija": [
            "Požeško-slavonska",
            "Virovitičko-podravska"
        ],
        "atrakcija": "Drenovačka utvrda Klak",
        "dogadjaj_godine": "Srednjovjekovni viteški turnir",
        "zivotinje": [
            {
                "naziv": "Močvarni plavac",
                "vrsta": "leptir"
            },
            {
                "naziv": "Pjegavi daždevnjak",
                "vrsta": "vodozemac"
            }
        ]
    },
    {
        "park": "Vransko jezero",
        "tip": "Park prirode",
        "godina_osnutka": 1999,
        "povrsina": 57,
        "vrh": {
            "naziv": null,
            "visina": null
        },
        "zupanija": [
            "Šibensko-kninska",
            "Zadarska"
        ],
        "atrakcija": "Kasnoantička kula Osridak",
        "dogadjaj_godine": "Sajam lokalnih proizvoda",
        "zivotinje": [
            {
                "naziv": "Čaplja",
                "vrsta": "ptica"
            },
            {
                "naziv": "Kravosas",
                "vrsta": "zmija"
            }
        ]
    }
]
